# Translations
This is an affine transform that simply shifts the position of an image.
We use OpenCV's cv2.warpAffine() to implement these transformations


In [15]:
import cv2
import numpy as np
image=cv2.imread('./images/input.jpg')
#store height & width of the image
height,width=image.shape[:2]
#print (height,width)
quarter_height,quarter_width=height/4,width/4
#print (quarter_height,quarter_width)

#  |1 0 Tx|
#T=|0 0 Ty|

#T is our translation matrix
T=np.float32([[1,0,quarter_width],[0,1, quarter_height]])

#we use cv2.warpAffine to perform the transformation

img_transform=cv2.warpAffine(image,T,(width,height))
cv2.imshow("Image Transformation",img_transform)
#lets take a look at T
print(T)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[  1.    0.   87.5]
 [  0.    1.   87.5]]


# Lets Rotate
OpenCV allows you to scale and rotate the same thing using the function
cv2.getRotationMatrix2D(rotation_center_x,rotation_center_y,angle of rotation,scale)


M=|cos@ -sin@;
   sin@ cons@|

In [18]:
import cv2
import numpy as np
image=cv2.imread('./images/input.jpg')
height,width=image.shape[:2]
#Divide by two to rotate the image around its centre
rotation_matrix=cv2.getRotationMatrix2D((width/2,height/2),90,1)
rotated_image=cv2.warpAffine(image,rotation_matrix,(width,height))

cv2.imshow("Rotated Image",rotated_image)
#lets take a look at T
print(rotation_matrix)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[  6.12323400e-17   1.00000000e+00  -2.84217094e-14]
 [ -1.00000000e+00   6.12323400e-17   3.50000000e+02]]


# To fit the image to the canvas size and avoid the image gettting cropped, we use the cv2.transpose()
However it does it only for 90 degree rotations


In [22]:
#other method
img=cv2.imread('./images/input.jpg')
rotated_image=cv2.transpose(img)
cv2.imshow("Rotated Image 2",rotated_image)
#lets take a look at T
print(rotation_matrix)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[  6.12323400e-17   1.00000000e+00  -2.84217094e-14]
 [ -1.00000000e+00   6.12323400e-17   3.50000000e+02]]


# Scaling, Re-sizing and Interpolations
Re-sizing is very easy using the cv2.resize(). It's arguments are:  
cv2.resize(image,dsize(output image size),x scale, y scale, interploation)


In [3]:
import cv2
import numpy as np
#Load our image
image=cv2.imread('./images/input.jpg')
#Let's make our image 3/4 of it's original size
image_scaled=cv2.resize(image,None,fx=0.75,fy=1)
cv2.imshow("Scaling - Linear Interpolation",image_scaled)
cv2.waitKey(0)


#Let's double the size of our image
img_scaled=cv2.resize(image,None,fx=2,fy=2,interpolation=cv2.INTER_CUBIC)
cv2.imshow("Scaling - Cubic Interpolation",img_scaled)
cv2.waitKey(0)

# Let's skew the re-sizing by setting exact dimensions 
img_scaled=cv2.resize(image,(900,400),interpolation=cv2.INTER_AREA)
cv2.imshow("Scaling - Skewed Size", img_scaled)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Image Pyramiding
It refers to either upscaling (enlarging) or downscaling(shrinking images).
  It's simply a diff. way of re-sizing that allows us to easily and quickly scale images.
   Useful in object detection to scale images each time it looks for an object
  

In [5]:
import cv2
image=cv2.imread('./images/input.jpg')

smaller=cv2.pyrDown(image) #convert to half its size (width & height)
larger=cv2.pyrUp(image) #Makes it twice the size of original image
cv2.imshow("Original", image)
cv2.imshow("Smaller", smaller)
cv2.imshow("Larger", larger)
cv2.waitKey(0)
cv2.destroyAllWindows()

